server:
  port: 8666
spring:
  profiles:
    active: dev
  #context-path: /springboot
---
#person:
#  last-name: hello
#  age: 18
#  boss: false
#  birth: 2019/03/01
#  maps: {k1: v1,k2: 12}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小狗
#    age: 12
server:
  port: 8081
spring:
  profiles: dev
---
server:
  port: 8082
spring:
  profiles: prod   #指定属于哪个环境